# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b03801b7deab67ec53e9905a68fdd01767492f10f155a687db83f48aff8c19e139660bd4b00395fd1c78220f93ee1fcc806087e25b736c22e3f42e62c3995e

test:
  secret_key_base: b6f5878298a061471b61447d69c4349c98b76fcb5e077d398510fd34e432e858e4f17f4266ec51822578c52f4eb89c3e001e55be81ef6948f3e148ddde984ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
